### PR TITLE
Restyling the application to look more like the prototype application.

### PR DESCRIPTION
**Pull request by DavidEBest**
This covers most of the 'basic' styles.

* Adding jquery-ui and updated jquery.
* Updated the topic endpoint to return the proposal id, if present for the user.
* Added image assets from the prototype.
* Replaced the rootscope controller property with an explicitly set bodyClass value.
* Added code to explicitly set the bodyClass value in controllers that could take advantage of it.
* Merge in the prototype css into the application, and restyled pages to use them.
* Correcting the formatting for the TPOC aside on the report page.
* Added the Delete the proposal button to the report page.
* Added formatting to the company page.

### CODE REVIEW

**Comment by andrewmaier** [comment]
Looking

**Comment by andrewmaier** [comment]
-Logo is a bit high (I can fix)
-Sign out link should have an href (will make it underlined)
-On the overview page, coversheet shouldn't be a link
- I owe you error states and a sidebar table of contents

**Comment by andrewmaier** [comment]
image

**Comment by andrewmaier** [comment]
checkbox

Checkboxes and radios need to have matching `name` attributes and unique `id` attributes.

**Comment by andrewmaier** [comment]
The signed out homepage has a grammatical error:

> The Small Business Innovation Research (SBIR) and Small Business Technology Transfer (STTR) programs encourages

Should be "encourage."

**Comment by andrewmaier** [comment]
I owe you pretty "sign in" styles and/or a sign in page.

**Comment by andrewmaier** [comment]
I should style the homepage to hide the header search bar.

**Comment by andrewmaier** [comment]
In general, this looks really great David. I know we've talked about making the company (or firm) pages [more like a wizard](https://codeforamerica.mybalsamiq.com/projects/sbir/Onboarding%20map) powered with API love. Are you waiting on me for any UI stuff there?

**Comment by DavidEBest** [comment]
Andrew - I will need some design support on that, but that'll be next sprint.

**Comment by juliaelman** [comment]
Here are some changes that I found need to be made throughout the site. Some may be higher priority than others and will let you all determine what you'd like to fix in this sprint :smile: 

Tabbing through on any page makes the header navbar disappear, see animated gif below:

wojapmwkzn

-------

Under "Firm Information" it looks like there is a light gray line on the right side? 

screen shot 2015-05-28 at 10 44 15 am

-------

The logged in homepage is not using aligned like the other pages and is completely left justified to the page.

screen shot 2015-05-28 at 10 48 49 am

-------

Under "My proposals", not sure if the lines under the links in the screenshot below are necessary?

screen shot 2015-05-28 at 10 51 42 am

**Comment by DavidEBest** [comment]
@juliaelman - Thanks for the review. I'll see if I can knock out the homepage and disappearing header issue asap!

**Comment by DavidEBest** [comment]
@juliaelman & @andrewmaier - I've addressed a few of the points that Julia brought up. Could I get you two to give 'em a once over?

**Comment by juliaelman** [comment]
@DavidEBest looks good!

**Pull request merged**
