### PR TITLE
Re-enabled validation and its tests

### PR DESCRIPTION
**Pull request by catherinedevlin**

### CODE REVIEW

**Comment by DavidEBest** [comment]
This re-enables the functionality, but where were the new partial save endpoints added?

**Comment by catherinedevlin** [comment]
The /proposals/partial/ endpoint still works with this branch - see ProposalTests.test_intentionally_incomplete_post in sbirez/test_api.py

**Comment by DavidEBest** [comment]
That works for creation, but we are still missing a `patch` able endpoint.

I can create a new proposal by `POST`ing data to `api/v1/proposals/partial/`, but if I try and `PATCH` a proposal at `api/v1/proposals/1/partial/` I get a `404 NOT FOUND`.

**Comment by catherinedevlin** [comment]
Good point - just pushed a patch enabling PATCH.

But incidentally, the URL is (currently) `api/v1/proposals/partial/1/`, not `api/v1/proposals/1/partial/`.  (Should it be the other way around?)

**Comment by DavidEBest** [comment]
Let's switch it. That way we can be consistent with the saved topic endpoint, which is `api/v1/topics/1/saved`.

**Comment by catherinedevlin** [comment]
Switched (finally).  Actually `/proposals/partial/<ID>/` and `/proposals/<ID>/partial/` will both work, but the latter can be the standard.

**Pull request merged**
